name: Snake Game

on:
  schedule:
    - cron: "0 0 * * *" # Atualiza diariamente
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: Platane/snk@master
        with:
          github_user_name: lucasgdsilva
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Commit e Push
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Atualizando animação da cobrinha"
          git push https://x-access-token:${TOKEN}@github.com/lucasgdsilva/lucasgdsilva.git HEAD:main
